"""empty message

Revision ID: 6704436bf262
Revises: 
Create Date: 2018-12-01 11:09:08.633523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6704436bf262'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('responsible', sa.String(length=32), nullable=True),
    sa.Column('tester', sa.String(length=32), nullable=True),
    sa.Column('func', sa.String(length=64), nullable=False),
    sa.Column('case_type', sa.SmallInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_item_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('glob_var', sa.String(length=512), nullable=True),
    sa.Column('glob_regx', sa.String(length=512), nullable=True),
    sa.Column('pre_command', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=4), nullable=False),
    sa.Column('hearders', sa.String(length=1024), nullable=True),
    sa.Column('data', sa.String(length=1024), nullable=True),
    sa.Column('post_command', sa.String(length=512), nullable=True),
    sa.Column('verify', sa.String(length=512), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=24), nullable=True),
    sa.Column('email', sa.String(length=24), nullable=True),
    sa.Column('password', sa.String(length=16), nullable=True),
    sa.Column('identity_id', sa.String(length=16), nullable=True),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('project')
    op.drop_table('case_item_request')
    op.drop_table('case')
    # ### end Alembic commands ###
