"""empty message

Revision ID: 91bc1cabde7b
Revises: 
Create Date: 2019-04-12 10:32:58.379555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91bc1cabde7b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('desc', sa.String(length=64), nullable=True),
    sa.Column('responsible', sa.String(length=32), nullable=True),
    sa.Column('tester', sa.String(length=32), nullable=True),
    sa.Column('case_type', sa.String(length=10), nullable=False),
    sa.Column('func', sa.String(length=64), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_project_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exec_date', sa.Date(), nullable=True),
    sa.Column('exec_time', sa.Time(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('pass_cases', sa.Integer(), nullable=True),
    sa.Column('fail_cases', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glob_var', sa.String(length=512), nullable=True),
    sa.Column('glob_regx', sa.String(length=512), nullable=True),
    sa.Column('pre_command', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=4), nullable=False),
    sa.Column('hearders', sa.String(length=1024), nullable=True),
    sa.Column('body', sa.String(length=1024), nullable=True),
    sa.Column('post_command', sa.String(length=512), nullable=True),
    sa.Column('verify', sa.String(length=512), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('case_requests')
    op.drop_table('case_record')
    op.drop_table('case_project_relation')
    op.drop_table('case')
    # ### end Alembic commands ###
